### ISSUE TITLE
Question: How I can install without X11 e.g. within docker container?

### ISSUE THREAD

**Issue by zeitiger** [dcevm/dcevm#109]
Hi guys,

is it possible to start the installer headless within a commandline? In my dev workflow I use docker to run my java daemons and struggle at the moment with hot redeployment with tomcat. I would like to give dcevm a try, but fail with the installer because of missing X11.

Best regards
David

**Comment by skybber** [comment]
You can unzip `DCEVM-light-8uXX-installer.jar`, go to `linux_amd64_compiler2/product` and copy `libjvm.so` to `${JAVA_HOME}/jre/lib/amd64/dcevm` direcotory

**Comment by zeitiger** [comment]
works 👍 
Thank you for you quick response.
Have a nice day

**Comment by rherrick** [comment]
It would be convenient if this were in the quick start docs rather than needing to find a closed issue report :)
