### ISSUE TITLE
Build error after applying light-jdk8u92-b14.patch

### ISSUE THREAD

**Issue by saqibahmed515** [dcevm/dcevm#117]
Hi,
I downloaded source for openjdk8u92-b14 from openjdk mercurial repositories and applied the patch light-jdk8u92-b14.patch on it using

patch -p1 <light-jdk8u92-b14.patch

It got patched successfully but build is failing after patching. The first error is due to java_lang_invoke_DirectMethodHandle_StaticAccessor field in jvmtiRedefineClasses2.cpp. I couldn't fint this class anywhere in the patch and/or source code. Am I doing something wrong? Or patch is faulty? Kindly help me building openjdk with DCEVM.

Regards

**Comment by saqibahmed515** [comment]
I got the answer. there were other patches too like dmh-field-accessors-java8.patch etc.

**Comment by skybber** [comment]
I would recommend you to apply all patches for 8u92 from [series](https://github.com/dcevm/dcevm/blob/master/hotspot/.hg/patches/series) as well jvmti-getLoadedClasses-java8.patch since it fixes major bug concerning debugging in IDE. jvmti-getLoadedClasses-java8.patch is used only for 8u122 but could be used for previous versions too.

**Comment by saqibahmed515** [comment]
So here's what I did:
1. Downloaded OpenJDKu92-b14 from mercurial repository.

2. Coppied **arguments-java8.patch**, **gc-java8.patch**, **dmh-field-accessors-java8.patch**, **JVM_SetVmMemoryPressure.patch**, **jvmti-getLoadedClasses-java8.patch** and **light-jdk8u92-b14.patch** in hotspot folder and applied these patches one by one using _patch -p1 < *.patch_ command. 

3. Finally configured and built the JDK. There was only one minor error remaining so I fixed it by hand. It was in file src/share/vm/gc_implementation/g1/heapRegion.cpp:1109.
I replaced 
----SCAN_AND_FORWARD(cp, top, block_is_always_obj, block_size); 
+++SCAN_AND_FORWARD(cp, top, block_is_always_obj, block_size, false);

Everything built successfully. I think this last change somehow slipped from the patch. Update the patch accordingly.

Now I'm on my way to use the so called Enhanced Redefinition API inside JVM for one of my projects. Is there any documentation or head starts available for using the API inside JVM????
Currently I can grab a class and/or a function and can get a pointer to it. My objective is to change it during runtime. Any help would be appreciated.

Regards
Saqib Ahmed

**Comment by skybber** [comment]
It is used over JVMTI in the same way in which the standard redefinition api is used. I would recommend you to look at original DCEVM project where you can find out more.

**Comment by saqibahmed515** [comment]
Sure, I would definitely see that. Actually I couldn't find any source which describes using standard JVMTI redefinition API inside JVM. I mean, I couldn't find the coding details for the sequence of pausing the threads on safepoints, changing metadata of class files, editing system dictionary and executing the edited bytecodes by resuming threads. 
I understand it theoretically, but couldn't grasp how to practice this theory.

Any enlightenment?

**Comment by skybber** [comment]
It is out of topic, you can write  me an email or contact me on HotswapAgent's gitter.

**Comment by saqibahmed515** [comment]
Email it is. Thanks for the help.
