### ISSUE TITLE
Unable to build with OpenJDK8-u112_b16 on OSX/MacOS (Travis-CI)

### ISSUE THREAD

**Issue by oranheim** [dcevm/dcevm#118]
I have tried a lot of different variations in order build DCEVM for Mac. I ended up creating a CI-build on Travis. Please check it out, as I have had no success to this point targeting OSX/MacOS 10.9 - 10.12 against OpenJDK8-u122_b16 and Oracle JDK 8-u122_b16. 

Travis build config:
https://github.com/descoped/descoped-dcevm/blob/master/.travis.yml

and

Build script:
https://github.com/descoped/descoped-dcevm/blob/master/build.sh

Build log with errors:
https://travis-ci.org/descoped/descoped-dcevm/builds/191018572

https://api.travis-ci.org/jobs/191018573/log.txt?deansi=true (raw log)

To me, it looks like linking errors. Any ideas on how to solve this?

**Comment by oranheim** [comment]
The Travis build is set up to run PRs, in case you [fork the sources](https://github.com/descoped/descoped-dcevm). 

You can follow the build results here: https://travis-ci.org/descoped/descoped-dcevm/builds

**Comment by idubrov** [comment]
Actually, I cannot build it myself anymore (on my Macbook laptop). I think, something has changed in core Mac OS X libraries so the build no longer works.

**Comment by oranheim** [comment]
Hi @idubrov! I see that you have released a new version of DCEVM. How can I build this myself. Can you share with me build instruction? That would help a great deal.

**Comment by skybber** [comment]
There is project dedicated to build dcevm8 on Travis now: https://github.com/TravaOpenJDK/trava-jdk-8-dcevm
