### ISSUE TITLE
Add official builds for Alpine Linux

### ISSUE THREAD

**Issue by randombk** [dcevm/dcevm#121]
A number of docker images now use Alpine Linux as the base image, which uses the musl libc instead of glibc. This makes it difficult to integrate DCEVM within an existing dockerized application environment, as DCEVM will need to be compiled specially for Alpine. Adding an official binary for Alpine would simplify this.

For reference, the error caused when using the linux_amd64 binary on Alpine is:
```
Error: dl failure on line 895
Error: failed /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server/libjvm.so, because Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server/libjvm.so)
```

**Comment by skybber** [comment]
Out of scope of this project
