### ISSUE TITLE
How do I install it on Apple MAC ?

### ISSUE THREAD

**Issue by PhilAndrew** [dcevm/dcevm#124]
Usually I use it on Windows but now suddenly I need to use an Apple MAC, how can I install this on the apple Mac?

Do I just launch the JAR as instructed here http://hotswapagent.org/index.html or do I need to build DCEVM on Mac? I hope I don't need to build to patch Java.

**Comment by idubrov** [comment]
Yes, just like that. You might need to run it with admin permissions & manually locate JDK/JRE location.
