### ISSUE TITLE
Doesn't work with icedtea 1.8.0_121 (at least on gentoo)

### ISSUE THREAD

**Issue by Barteks2x** [dcevm/dcevm#126]
Trying to run dcevm on icedtea (which accirding to openjdk website is a variant on openjdk, whatever it means) results in this error:
```
# java -XXaltjvm=dcevm -version
Error occurred during initialization of VM
java.lang.UnsatisfiedLinkError: sun.misc.Unsafe.isBigEndian0()Z
	at sun.misc.Unsafe.isBigEndian0(Native Method)
	at sun.misc.Unsafe.<clinit>(Unsafe.java:1233)
	at sun.misc.SharedSecrets.<clinit>(SharedSecrets.java:47)
	at java.lang.ref.Reference.<clinit>(Reference.java:235)
```
java -version output without dcevm:
```
# java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (IcedTea 3.3.0) (Gentoo icedtea-3.3.0)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by skybber** [comment]
Sorry for delay:) Dcevm8 is built for x86-64, is it really your architecture?

**Comment by skybber** [comment]
Thanks, btw, deopt can be tuned using `-XX:HotswapDeoptClassPath=...`

**Comment by Barteks2x** [comment]
I will test `-XX:HotswapDeoptClassPath=...` when I get around trying DCEVM again, but it's very likely the performance critical parts of code are also the parts of code that can be modified with my hotswap (but I usually wouldn't do that) so it's unlikely to help a lot.
