### ISSUE TITLE
Issue in installation

### ISSUE THREAD

**Issue by RaviDhaka** [dcevm/dcevm#129]
Hi 
I tried installing dcevm with java 1.8.0_112 and 131 as well but when i check java version from command prompt it does not states any altjvm.
Please help

**Comment by ducquoc** [comment]
Hi Ravi, 
Don't panic! 
Some newer versions of Java 8 (like _131) may not show with the "Dynamic ..." text banner with "java -version", but you can still check if the DCE VM exists by: 
```
  java -h 
```
then you can see in the output like this:

```
...
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -server	  to select the "server" VM
    -zero	  to select the "zero" VM
    -jamvm	  to select the "jamvm" VM
    -dcevm	  to select the "dcevm" VM
...
```

If you see the **-dcevm** then it is already installed. 

Besides, the plugins (like HotswapAgent of IntelliJ IDEA) can detect the DCEVM as well. You can see it show the versions like "25.71-b01-dcevmlight-8" . 

-Duc

**Comment by RaviDhaka** [comment]
Hi Duc,

DCEVM works with all the versions of java even without hotswapagent.

Thanks
Ravi

**Comment by nulinuli-nuli** [comment]
> Hi Ravi, Don't panic! Some newer versions of Java 8 (like _131) may not show with the "Dynamic ..." text banner with "java -version", but you can still check if the DCE VM exists by:
> 
> ```
>   java -h 
> ```
> 
> then you can see in the output like this:
> 
> ```
> ...
> where options include:
>     -d32	  use a 32-bit data model if available
>     -d64	  use a 64-bit data model if available
>     -server	  to select the "server" VM
>     -zero	  to select the "zero" VM
>     -jamvm	  to select the "jamvm" VM
>     -dcevm	  to select the "dcevm" VM
> ...
> ```
> 
> If you see the **-dcevm** then it is already installed.
> 
> Besides, the plugins (like HotswapAgent of IntelliJ IDEA) can detect the DCEVM as well. You can see it show the versions like "25.71-b01-dcevmlight-8" .
> 
> -Duc

I tried installing dcevm with java 1.8.0_112 and 131 as well and   java -h not show   -dcevm，how can i do with other way
