### ISSUE TITLE
some confuse about the code in gc-java8u40.patch

### ISSUE THREAD

**Issue by wuyan0** [dcevm/dcevm#130]
hi, I’m reading source code and get some confuse.
[there](https://github.com/dcevm/dcevm/blob/master/hotspot/.hg/patches/gc-java8u40.patch#L133)  in MarkSweep::update_fields. why copy the data from a new array to the old oop？ is the direction opposite？

```
tmp = NEW_RESOURCE_ARRAY(HeapWord, size);
q = (oop) tmp;
Copy::aligned_disjoint_words((HeapWord*)q, (HeapWord*)tmp_obj, size);
```

[the other one](https://github.com/dcevm/dcevm/blob/master/hotspot/.hg/patches/gc-java8u40.patch#L214) in GenMarkSweep::mark_sweep_phase4

```
MarkSweep::copy_rescued_objects_back();

GenCompactClosure blk;
gch->generation_iterate(&blk, true);

MarkSweep::copy_rescued_objects_back();
```

[there](https://github.com/dcevm/dcevm/blob/master/hotspot/.hg/patches/gc-java8u40.patch#L208) already assert the _rescued_oops is null, so why need to copy rescued oops back?

Thanks

**Comment by idubrov** [comment]
Looks like you are right! The first one does indeed look like a bug -- I'll try to fix it and verify using the tests I have (if I can get my Mac OS X environment to work again...).

The second one is harmless as copy_rescued_objects_back will be essentially a no-op on the first invocation, but still, it looks like a bug, too.

Thanks for your review :)

**Comment by idubrov** [comment]
Fixed in master & created a new release.
