### ISSUE TITLE
Spring MVC annotations (@RequestMapping) + HotswapAgent not support

### ISSUE THREAD

**Issue by wagamama06** [dcevm/dcevm#132]
I use DCEVM + HotswapAgent width Spring MVC project. It is working smoothly. But it does not reflect online When I change @RequestMapping value . 

My project:  Spring Mvc Maven 4X Project , jdk1.8.0_144 , hotswap-agent-1.1.0

**Comment by skybber** [comment]
This is HotswapAgent issue, not DCEVM. Pls close it and open for HA.

**Comment by wagamama06** [comment]
ok. Thanks.
