### ISSUE TITLE
Cannot get latest DCEVM to hook up with JDK 1.8.0_151 for MAC X 64

### ISSUE THREAD

**Issue by Mrc2** [dcevm/dcevm#136]
Using the Replace by DCEVM and Install DCEVM as altjvm fail verses Mac 10.13.1 High Sierra and the latest JDK 8 jvm fails. :( 

Any Ideas on how to resolve this as you cannot change the rights to libjvm.dylib to create libjvm.dylib.backup ? 
![image](https://user-images.githubusercontent.com/2110421/32901513-9794d12a-cab5-11e7-9f46-161a06ae19fa.png)

**Comment by arielcarrera** [comment]
Tested with jdk 8u144 and DCEVM-8u144-installer.jar and it works OK on a Mac Os X High Sierra.

Remember to execute JAR with "sudo java -jar DCEVM-8u144-installer.jar"

**Comment by Mrc2** [comment]
circling back after a long time.  Have been uses for months now.

DCE rocks :)

**Comment by przemelek** [comment]
We skipped 151, closest one is 152.
In general you should use only DCEVM for given JVM version.
DCEVM replaces (or alters if you are using -XXaltjvm=dcevm) library with JVM with our own version. 
So DCEVM for different JVM version may work, but it may not.

**Comment by Mrc2** [comment]
I adopted DCEVM 152 and JVM 152 previously without problems.
