### ISSUE TITLE
Unable to uninstall DCEVM-full-7u79-installer

### ISSUE THREAD

**Issue by gaurav9822** [dcevm/dcevm#141]
I had Installed DCEVM-full-7u79-installer.jar and now want to revert to Oracle Hotspot VM.

But, when I click uninstall, it pops up with the error:

> Please ensure that no other Java applications are running and you have sufficient permissions.

Steps followed:
- Replaced by DCEVM? Yes(24.79-b02-dcevmfull-8)
- Installed altjvm? Yes(24.79-b02-dcevmfull-8)

P.S. Running DCEVM-full-7u79-installer.jar as an administrator.

**Comment by skybber** [comment]
All the installer does is copying jvm lib to dcevm in openjdk directory structure. You could fix it by removing this directory.
