### ISSUE TITLE
 A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by kalwar** [dcevm/dcevm#143]
Hi

Anyone know why this is happening in MAC

[INFO] # A fatal error has been detected by the Java Runtime Environment:
[INFO] #
[INFO] #  SIGSEGV (0xb) at pc=0x00000001066ea2b7, pid=9698, tid=0x000000000000a903
[INFO] #
[INFO] # JRE version: OpenJDK Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
[INFO] # Java VM: Dynamic Code Evolution 64-Bit Server VM (25.71-b01-dcevmlight-2 mixed mode bsd-amd64 compressed oops)
[INFO] # Problematic frame:
[INFO] # V  [libjvm.dylib+0x2ea2b7]  klassItable::initialize_itable_for_interface(int, KlassHandle, bool, Thread*)+0x41
[INFO] #
[INFO] # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
[INFO] #
[INFO] # An error report file with more information is saved as:
[INFO] # /Users/tespok/java/myapp/hs_err_pid9698.log
[INFO] #
[INFO] # If you would like to submit a bug report, please visit:
[INFO] #   https://github.com/dcevm/dcevm/issues
[INFO] #

**Comment by kalwar** [comment]
Seeing something like these:

`SIGHUP: [libjvm.dylib+0x389aa4], sa_mask[0]=11111111011111110111111111111111, sa_flags=SA_RESTART|SA_S
 
SIGINT: [libjvm.dylib+0x389aa4], sa_mask[0]=11111111011111110111111111111111, sa_flags=SA_RESTART|SA_S
 
SIGTERM: [libjvm.dylib+0x389aa4], sa_mask[0]=11111111011111110111111111111111, sa_flags=SA_RESTART|SA_
 
SIGQUIT: [libjvm.dylib+0x389aa4], sa_mask[0]=11111111011111110111111111111111, sa_flags=SA_RESTART|SA_
 
 
---------------  S Y S T E M  ---------------
 
OS:Bsduname:Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41
 
rlimit: STACK 8192k, CORE 0k, NPROC 1418, NOFILE 10240, AS infinity
 
load average:6.17 4.21 5.73
 
CPU:total 4 (initial active 4) (2 cores per cpu, 2 threads per core) family 6 model 61 stepping 4, cmo
 
Memory: 4k page, physical 16777216k(86804k free)
 
/proc/meminfo:
 
vm_info: Dynamic Code Evolution 64-Bit Server VM (25.71-b01-dcevmlight-2) for bsd-amd64 JRE (1.8.0), b
 
time: Mon May  7 13:49:49 2018
 
elapsed time: 76 seconds (0d 0h 1m 16s)`

**Comment by skybber** [comment]
hs_err_pid*.log must be supplied next time.
