### ISSUE TITLE
Fatal Error SIGSEGV

### ISSUE THREAD

**Issue by gpolito** [dcevm/dcevm#149]
Hi guys,

Could you please help me to detect what's root cause of this issue?
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f404a0bd297, pid=6952, tid=0x00007f3f948a2700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_172-b11) (build 1.8.0_172-b11)
# Java VM: Dynamic Code Evolution 64-Bit Server VM (25.71-b01-dcevmlight-14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x61c297]  InstanceKlass::link_class(Thread*)+0x17
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/guillermo-polito/Pyxis/Belimo/belimo-project/belimo/hybris/bin/platform/tomcat/bin/hs_err_pid6952.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/dcevm/dcevm/issues
```
This is the [link](https://www.dropbox.com/s/owp07k7nwi083uh/hs_err_pid6952.log?dl=0) to the log file.

This is the JVM I'm using, with the DCEVM-8u172: 
```
$ java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

Thanks in advance.

**Comment by skybber** [comment]
JVM crashes in redefinition. What kind of code modification did you do? Are you able to reproduce the problem?

**Comment by gpolito** [comment]
Hi @skybber : 
I'm working in a JUnit Test Class. This happens when I do any change inside the class.

**Comment by skybber** [comment]
Do  you have same problem with previous version - dcevm8.152?

**Comment by przemelek** [comment]
@gpolito can you share with more details?
Just moment ago tried on my Ubuntu with JDK8u172 and DCEVM running some UnitTests with JUnit without problems.
Can you for example share some code snippets which are making problems on your system?

**Comment by skybber** [comment]
Not enough information to solve this issue, I'm closing it
