### ISSUE TITLE
DCEVM + HotSwap Agent on Glassfish 3 crashes attaching debugger

### ISSUE THREAD

**Issue by manusoftar** [dcevm/dcevm#151]
Whenever i try to attach a debbuger to my glassfish 3.1.2 it crasher with the following error

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000000292ab2d, pid=35572, tid=36460
#
# JRE version: Java(TM) SE Runtime Environment (7.0_79-b15) (build 1.7.0_79-b15)
# Java VM: Dynamic Code Evolution 64-Bit Server VM (24.79-b02-dcevmfull-8 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# j  java.lang.Thread.exit()V+12
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Glassfish3_1_2\glassfish\domains\domain1\config\hs_err_pid35572.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Please use CMSClassUnloadingEnabled in place of CMSPermGenSweepingEnabled in the future
Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "HotSwap Watcher"
```

Im working with Java 1.7_79 since Glassfish 3 only supports up to Java 7 but not 8, im using Hibernate 3, Spring, Logback, Log4J (on different proyects), JSP, Servlets.

My projects are Maven based, they where working properly prior to installing DCEVM with jRebel but since their free license has ended i had to move on to an alternative and DCEVM with HotSwap seemed to me to be the best choice...

I can start Glassfishon debug mode but without attaching an actual debugger, whenever i try to attach the debugger (Im working with Netbeans 8.2 on Windows 7 x64) it crashes.

If i make changes they are properly updated by DCEVM but i need to be able to debug my apps.

Just in case [here](https://pastebin.com/tzaxCshi) is the extended log.

Thanks in advance for any help you may give me on this issue.

**Comment by skybber** [comment]
You can try last dcevm7 version and check if dcevm build version matches your openjdk version. It must be same. Anyway we don't support java7 anymore.

**Comment by manusoftar** [comment]
Im using Oracle JDK and i installed the version 1.7u79 specifically so it matched the latest dcevm7 version (if im not wrong).

**Comment by skybber** [comment]
You could try light version instead of full. It is more lightweight then full and probably cover all your needs. (it's not clear where the problem is...)

**Comment by skybber** [comment]
dcevm7 is retired in another repo
