### ISSUE TITLE
Can't install on macOS

### ISSUE THREAD

**Issue by grobmeier** [dcevm/dcevm#155]
I downloaded the installer, opened it. The below screen appears. I then choose an installation directory and hit the button "choose". Then I am returned to the below screen, without any selection. Thus, I cannot continue the installation.

On the background log, you can see

`Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: /Users/<...>/DCEVM is no JRE or JDK-directory.
	at com.github.dcevm.installer.Installation.<init>(Installation.java:68)
	at com.github.dcevm.installer.AddDirectoryAction.actionPerformed(AddDirectoryActi`

Choosing the Home folder of my JRE would fix it, except I need to run the installer in root mode.

I would like to suggest to improve the installers wording to say you'll need to chose a HOME folder of the JRE and not just installation directory. Furthermore I'd like to suggest to tell you might need to use root privileges. Lastly these messages are not visible on the screen itself, it's only visible when you start it from command line. When you start the application by just clicking it, you'll not see any feedback.

![image](https://user-images.githubusercontent.com/873786/43942805-ae36d11c-9c79-11e8-84be-dc06c9b69312.png)

**Comment by przemelek** [comment]
We changed installer in such way that now on macOS it will scan all subfolders, so you should be OK to set something higher... but if you are using standard locations on macOS it should now find those when it starts.
Latest version of DCEVM for Java 8u181 https://github.com/dcevm/dcevm/releases/tag/light-jdk8u181%2B2 is doing it.
