### ISSUE TITLE
How to install with Docker image "jboss/wildfly:12.0.0.Final"?

### ISSUE THREAD

**Issue by willsilvano** [dcevm/dcevm#161]
Hi,

i'm trying to install with Docker image "jboss/wildfly:12.0.0.Final" but don't work.

How can I do it?

Tks.

**Comment by przemelek** [comment]
Download JAR ( for example with wget https://github.com/dcevm/dcevm/releases/download/light-jdk8u181%2B2/DCEVM-8u181-installer-build2.jar)
unzip DCEVM-8u181-installer-build2.jar
mv linux_amd64_compiler2/product/libjvm.so <placeWhereYourJVMHavaFile_libjvm.so>

all those during creation of image

**Comment by skybber** [comment]
Or you can look at https://github.com/HotswapProjects/hotswap-docklands, there are prepared base images for Wildfy + dcevm + HotswapAgent

**Comment by skybber** [comment]
Another option is to use https://github.com/anapsix/docker-alpine-java as base image. There is also dcevm + HotswapAgent

**Comment by willsilvano** [comment]
> linux_amd64_compiler2/product/libjvm

Returning this erros:

Error: missing `dcevm' JVM at `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre/lib/amd64/dcevm/libjvm.so'.

**Comment by willsilvano** [comment]
My Dockerfile:

FROM jboss/wildfly:12.0.0.Final

ENV JBOSS_HOME /opt/jboss/wildfly
ENV TZ=America/Sao_Paulo

COPY jboss/standalone.xml /opt/jboss/wildfly/standalone/configuration
COPY postgresql-42.2.1.jar /opt/jboss/wildfly/standalone/deployments
ADD --chown=jboss glowroot /opt/jboss/glowroot

COPY hibernate-orm-modules-5.2.17.Final-wildfly-11-dist.zip /opt/jboss/wildfly/modules

RUN /opt/jboss/wildfly/bin/add-user.sh user pass --silent
RUN unzip /opt/jboss/wildfly/modules/hibernate-orm-modules-5.2.17.Final-wildfly-11-dist.zip -d /opt/jboss/wildfly/modules/

USER root

RUN mkdir -p /opt/HotswapAgent/ 
COPY DCEVM-8u181-installer-build2.jar /opt/HotswapAgent/
RUN unzip /opt/HotswapAgent/DCEVM-8u181-installer-build2.jar -d /opt/HotswapAgent/DCEVM/
RUN mv /opt/HotswapAgent/DCEVM/linux_amd64_compiler2/product/libjvm.so ${JAVA_HOME}/jre/lib/amd64/dcevm

ENV JAVA_OPTS -server -Xms2g -Xmx2g -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -XXaltjvm=dcevm -javaagent:/opt/HotswapAgent/DCEVM-8u181-installer-build2.jar

RUN localedef -c -i pt_BR -f UTF-8 pt_BR.UTF-8

ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR:pt
ENV LC_ALL pt_BR.UTF-8

EXPOSE 8080
EXPOSE 9990
EXPOSE 8787

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]

**Comment by willsilvano** [comment]
Hi @skybber 
It's work with  https://github.com/anapsix/docker-alpine-java
But, the resources (xhtml) are not updating.
Need any extra configuration?

**Comment by willsilvano** [comment]
Where I should put this config?
https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/resources/hotswap-agent.properties

I have multiple projects in same project.
I don't have a src/main/resource folder...

Tks.

**Comment by skybber** [comment]
For out-of-docker xhtml reloading you need setup webappDir config parameter. But it  is not supported on Wildfly yet. Currently this parameter works only on app servers based on WebAppClassLoader (Tomcat, Tomee, GlassFish, Payara and Jetty). I have it on my TODO list. If you are interested [JBossModules plugin](https://github.com/HotswapProjects/HotswapAgent/tree/master/plugin/hotswap-agent-jbossmodules-plugin/src/main/java/org/hotswap/agent/plugin/jbossmodules) must me fixed similarly like TomcatPlugin.

**Comment by willsilvano** [comment]
Hi @skybber . I'll wait for this feature. Thanks!

**Comment by skybber** [comment]
OK, please make issue in HA issues

**Comment by willsilvano** [comment]
Hello @skybber ! Do you have any prediction of when we will have this improvement? 
We already tested several alternatives to hotswap and the best was this one. 
The only problem is that it is not doing the hotsawp from css / html / js files.

**Comment by skybber** [comment]
I'll try to do it for next release (in may-june), it looks like desired feature. What's your technology stack?

**Comment by willsilvano** [comment]
Hi @skybber , that's nice!

My current stack is :
- Wildfly 12.0.0.Final
- Primefaces 6.2
- JSF 2.3
- Hibernate 5.2.17.Final

**Comment by skybber** [comment]
Last 1.3.1-SNAPSHOT version has supports webappDir for undertow (Wildfly, Swarm, Quarkus...). Could you check your case?

**Comment by willsilvano** [comment]
Hi @skybber , thanks !! I'll try this as son as possible!

**Comment by willsilvano** [comment]
Hi @skybber !
I tried to up my Docker image, but this get this error:

`Error: missing `dcevm' JVM at `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/amd64/dcevm/libjvm.so`

**Comment by skybber** [comment]
it looks like problem of your docker image. Could you create small docker project demonstrating this problem?

**Comment by willsilvano** [comment]
Hi, it works now!
I had done a wrong config on my Docker image.
But I think the hotswap is not working.
My Docker image:

> FROM jboss/wildfly:12.0.0.Final

> ENV JBOSS_HOME /opt/jboss/wildfly
ENV TZ=America/Sao_Paulo

> USER root

> COPY sgn-web/target/sgn3.war ${JBOSS_HOME}/standalone/deployments

> COPY docker/wildfly/standalone.xml ${JBOSS_HOME}/standalone/configuration

> COPY docker/database/postgresql-42.2.1.jar ${JBOSS_HOME}/modules/system/layers/base/org/postgresql/main/
COPY docker/database/module.xml ${JBOSS_HOME}/modules/system/layers/base/org/postgresql/main/

> COPY docker/database/hibernate-orm-modules-5.2.17.Final-wildfly-11-dist.zip ${JBOSS_HOME}/modules
RUN unzip ${JBOSS_HOME}/modules/hibernate-orm-modules-5.2.17.Final-wildfly-11-dist.zip -d ${JBOSS_HOME}/modules/

> COPY docker/dcevm/hotswap-agent-1.3.1-SNAPSHOT.jar /opt/HotswapAgent/
COPY docker/dcevm/libjvm.so /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/amd64/dcevm/

> ADD --chown=jboss docker/glowroot /opt/jboss/glowroot

> RUN ${JBOSS_HOME}/bin/add-user.sh user pass --silent

> ENV JAVA_OPTS -Xms2g -Xmx2g -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -XXaltjvm=dcevm -javaagent:/opt/HotswapAgent/hotswap-agent-1.3.1-SNAPSHOT.jar

> RUN localedef -c -i pt_BR -f UTF-8 pt_BR.UTF-8
ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR:pt
ENV LC_ALL pt_BR.UTF-8

> USER jboss

> ENTRYPOINT ${JBOSS_HOME}/bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0 --debug

**Comment by skybber** [comment]
Are you using  `extra_class_path` ? Look at https://github.com/HotswapProjects/hotswap-docklands how to do that.

**Comment by willsilvano** [comment]
My project have multiple modules, how can I configure the `extra_class_path`?

My `docker-compose.yml`:

```
version: '2'

services:
  
  sgn3:    
    container_name: sgn3
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./sgn-web/target/classes:/extra_class_path
      - ./sgn-web/target/sgn3.war:/opt/jboss/wildfly/standalone/deployments/sgn3.war
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8081"
      - "9091:9091"
      - "8787:8787"
```

My `Dockerfile`:

```
FROM jboss/wildfly:12.0.0.Final

ENV JBOSS_HOME /opt/jboss/wildfly
ENV TZ=America/Sao_Paulo

USER root

COPY sgn-web/target/sgn3.war ${JBOSS_HOME}/standalone/deployments

COPY docker/wildfly/standalone.xml ${JBOSS_HOME}/standalone/configuration

COPY docker/database/postgresql-42.2.1.jar ${JBOSS_HOME}/modules/system/layers/base/org/postgresql/main/
COPY docker/database/module.xml ${JBOSS_HOME}/modules/system/layers/base/org/postgresql/main/

COPY docker/database/hibernate-orm-modules-5.2.17.Final-wildfly-11-dist.zip ${JBOSS_HOME}/modules
RUN unzip ${JBOSS_HOME}/modules/hibernate-orm-modules-5.2.17.Final-wildfly-11-dist.zip -d ${JBOSS_HOME}/modules/

COPY docker/dcevm/hotswap-agent-1.3.1-SNAPSHOT.jar /opt/HotswapAgent/
COPY docker/dcevm/libjvm.so /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/amd64/dcevm/

ADD --chown=jboss docker/glowroot /opt/jboss/glowroot

RUN ${JBOSS_HOME}/bin/add-user.sh user pass --silent

ENV JAVA_OPTS -Xms2g -Xmx2g -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -XXaltjvm=dcevm -javaagent:/opt/HotswapAgent/hotswap-agent-1.3.1-SNAPSHOT.jar -Dextra.class.path=/extra_class_path

RUN localedef -c -i pt_BR -f UTF-8 pt_BR.UTF-8
ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR:pt
ENV LC_ALL pt_BR.UTF-8

USER jboss

ENTRYPOINT ${JBOSS_HOME}/bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0 --debug
```
I've added `-Dextra.class.path=/extra_class_path` on `JAVA_OPTS`

**Comment by willsilvano** [comment]
The agent is configured:

```
$ docker-compose up

Creating network "sgn3-docker_default" with the default driver
Creating sgn3 ... done
Attaching to sgn3
sgn3    | JAVA_OPTS already set in environment; overriding default settings with values: -Xms2g -Xmx2g -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8 -Djava.
net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -XXaltjvm=dcevm -javaagent:/opt/HotswapAgent/hotswap-agent-1.
3.1-SNAPSHOT.jar -Dextra.class.path=/extra_class_path
sgn3    | =========================================================================
sgn3    | 
sgn3    |   JBoss Bootstrap Environment
sgn3    | 
sgn3    |   JBOSS_HOME: /opt/jboss/wildfly
sgn3    | 
sgn3    |   JAVA: /usr/lib/jvm/java/bin/java
sgn3    | 
sgn3    |   JAVA_OPTS:  -server -Xms2g -Xmx2g -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.
jboss.byteman -Djava.awt.headless=true -XXaltjvm=dcevm -javaagent:/opt/HotswapAgent/hotswap-agent-1.3.1-SNAPSHOT.jar -Dextra.class.path=/extra_class_path -ag
entlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
sgn3    | 
sgn3    | =========================================================================
sgn3    | 
sgn3    | HOTSWAP AGENT: 12:55:56.872 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.3.1-SNAPSHOT} - unlimited runtime class redefinition.
sgn3    | HOTSWAP AGENT: 12:55:58.056 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow]
sgn3    | Listening for transport dt_socket at address: 8787
```

**Comment by skybber** [comment]
Looks good except extra class path definition. It should be:

   -DextraClasspath=/extra_class_path

Where did you find `-Dextra.class.path` ?

**Comment by skybber** [comment]
I see the problem now, probabyl there should be 

    extraClasspath=${extra.class.path}

in hotswap-agent.properties

**Comment by willsilvano** [comment]
I found that here: https://github.com/skybber/ping/blob/master/Dockerfile

**Comment by willsilvano** [comment]
I need IDE, like IntelliJ, to get it work?

**Comment by skybber** [comment]
Please, send me email to not spam dcevm issues.
