### ISSUE TITLE
HotSwapping Jar File - No changes

### ISSUE THREAD

**Issue by mircoianese** [dcevm/dcevm#163]
Hello, 
I'm new to dcevm, so sorry if I'm doing something wrong. I'm trying to hot-swap a running Jar in order to make silent updates to my program. I've downloaded last Linux JDK11 build and I'm using it to start a JAR file like this:

`./dcevm/bin/java -jar JarFile.jar` --> The program starts as it should

Then I tried to make some changes to the code (I've edited a text that was printed), I've recompiled the JAR file (using Maven) and I've replaced the original Jar file with the new one while the program was running. 

The program did not crashed, nor I saw strange errors in console, but the text did not changed (so it seems like it's not reloading the Classes.

Am I missing something? 
Thanks

**Comment by skybber** [comment]
Look at http://hotswapagent.org/mydoc_quickstart.html and http://hotswapagent.org/mydoc_configuration.html . Replacing jar does not work, try to use `extraClasspath` pointing to your compiled classes. Probably you will need `autoHotswap=true`, if you don't run it in debug session.
