### ISSUE TITLE
Question: GraalVM + DCEVM?

### ISSUE THREAD

**Issue by jsundqvist** [dcevm/dcevm#164]
Hello, I'm writing a web stack based on GraalVM where I have JS running on both client and server.

I would like to have DCEVM for hot reloading of Java on the server side. Will this be possible?

I'm willing to give it a try but I suspect that the internals of GraalVM are vastly different to what DCEVM is built for. What is the current status?

Thank you for an awesome project!

**Comment by skybber** [comment]
I didn't check it, but DCEVM is fix of Hotspot and GraalVM is JIT for Hotspot, if it is so, then it is doable. But nobody of us try it.

**Comment by jsundqvist** [comment]
Thank you for your answer.

I will try it and report my findings.

/Johannes
