### ISSUE TITLE
Support for openjdk version "1.8.0_212" ?

### ISSUE THREAD

**Issue by marcjohnen** [dcevm/dcevm#166]
I was a happy user of dcevm until I installed Ubuntu 19.04.
It only supports openjdk version "1.8.0_212" or openjdk 11 (which doesn't support the software I have to use).
Is there a way to get dcevm to work with this openjdk version? Will there be an updated release?
I haven't been able to get this to work.
Thanks
Marc

**Comment by skybber** [comment]
Look at https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases, there is build dcevm8u202b08 compatible at least up to 1.8u222. (I'm just not sure if existing dcevm 1.8u181 installation is binary compatible with 1.8u212.) And do following steps

- extract `java8-openjdk-dcevm-linux.tar.gz`
- copy `jre/lib/amd/server/libjvm.so` to `dcevm` directory in your JVM installation (in my case it is /usr/lib/jvm/java-8-openjdk/jre/lib/amd64/dcevm). `dcevm` directory is directory for alternative JVM recognized by `-XXaltjvm=dcevm`

**Comment by marcjohnen** [comment]
So I installed https://github.com/dcevm/dcevm/releases/download/light-jdk8u181/DCEVM-8u181-installer.jar
then downloaded java8-openjdk-dcevm-linux.tar.gz from https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases and copied the jre/lib/amd/server/libjvm.so it contains to /usr/lib/jvm/java-8-openjdk/jre/lib/amd64/dcevm as you suggested.
For now it looks like it works. 
Thanks a lot.

**Comment by skybber** [comment]
You can skip procedure with the DCEVM-8u181-installer.jar, since all it does is to copy `libjvm.so` to dcevm directory.
