### ISSUE TITLE
Extend Installer for SAP JVM

### ISSUE THREAD

**Issue by DenisZygann** [dcevm/dcevm#168]
Hi,

I'm need to use the SAP JVM. Could you add in the ConfigurationInfo.is64Bit() if the -version contains also the string amd64.

Here is my version Output:
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 8.1.055)
SAP Java Server VM (build 8.1.055 10.0.2+000, May  6 2019 12:06:19 - 81_REL - optU - linux amd64 - 6 - bas2:315134 (mixed mode))

Thanks in advance.

**Comment by skybber** [comment]
Could you please create PR ? We have no opportunity to test it. Thanks

**Comment by DenisZygann** [comment]
Do I have to push my feature into the master directly?
I would like to create a feature branch,  but I'm not allowed to do it.

**Comment by skybber** [comment]
Could you fork repo and make pull request as it is common workflow on github?

**Comment by skybber** [comment]
done
