### ISSUE TITLE
Does not work to apply patch on Mac OS Mojave, 10.14.6 (18G84)

### ISSUE THREAD

**Issue by aiboogie** [dcevm/dcevm#171]
Started installer, which identifies installed java folders, but says "Could not get javaversion....".
Installed altjvm says the same: "Yes (Could not get dceversion of /Library...).

Tried with open jdk 11.

Please advise.
Thank you.

**Comment by przemelek** [comment]
Sorry, but it seems from short description that you are trying to use GUI installer. This installer is available only for DCEVM for Java 8.

DCEVM for Java 11 is available as whole JVM, you may find it here https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases
You install it alongside normal JVM, and use normal JVM to run programs, and JVM with DCEVM to run apps where you are using DCEVM.
