### ISSUE TITLE
GUI unable to install on MAC OS X

### ISSUE THREAD

**Issue by Nexowned** [dcevm/dcevm#173]
<img width="912" alt="Screen Shot 2019-09-21 at 12 25 42" src="https://user-images.githubusercontent.com/49051663/65378327-a804a980-dc6b-11e9-9515-b82f2e4aeda8.png">

Hello I just came across this from a friend to start setting up HotSwap in use with intellij, but also have to download this in order to use. But i keep getting this error. I set suffice permissions but still getting this..
Any help on this issue would be greatly appreciated! Thanks for the look

Also is it just possible I can unpack the jar? or will that not work..

**Comment by przemelek** [comment]
@Nexowned can you check if you are running it as root? I'm not sure if you are able to set access for something in /Library to one of users (other thing is, I tested changes in this code about year ago, so it is possible that I don't remember everything ;-))

**Comment by Nexowned** [comment]
By default my terminal should be running as root. 
Im able to extract the jar and get the packages from it.
If i have to go that route, how would i implement the correct paths?
Do i just make 'dcevm' directory in my JRE and add the 'libjvm.dylib' to that folder and it should run?
Thank You so much for the fast response <3

**Comment by Nexowned** [comment]
UPDATE: running the application via 'sudo' (root) did not do the trick...

**Comment by Nexowned** [comment]
So where would the code import the dynamic library too ? i guess since the installer wont work, i took a look at the code but i couldn't decipher would directory it would be placed into to make the proper paths and compatibility properly work

**Comment by Nexowned** [comment]
AHA! I figured it out, i just ended up making an alias java folder on my desktop, apprently it is true that you cannot write to /Library... Maybe we could implement that fix in the code? I will add this later on if you are willing to accept minor changes :) Thanks for the fast reply netherless <3 Enjoy your day / night! !

**Comment by Nexowned** [comment]
You can close this Issue request, Thanks for your help but i was just a bit retarted and assumed that the folder already had the correct permissions, little did i know i needed to include ALL folders for that permission under admin/root.... 
Great product by the way and im looking forward to switching from jdk8 to jdk11 to try out the updated version!<3
Thanks very much and good luck on your endeavors
Regards,
Ian

**Comment by Nexowned** [comment]
One more question before you close this, Is this available with the most up to date version of Jdk8 which is u221 i believe?

**Comment by przemelek** [comment]
Nope, one thing would be to move DCEVM to Java 8u221, other thing would be to make builds for all OSes. 
Maybe will play around with moving sources to u221, but without any promises.
