### ISSUE TITLE
DCEVM license type

### ISSUE THREAD

**Issue by jhefreyzz** [dcevm/dcevm#175]
Hi,

I like to try using this software but there is no specified license for it.

May I know what license does this project used for the software?

Thank you very much.

**Comment by skybber** [comment]
You are right, LICENCE file is missing here. But any OpenJDK's modification MUST be licenced by original licence. We have repository with dcevm patch as branch from original OpenJDK, where you can find it's licence file:

https://github.com/HotswapProjects/openjdk-jdk8u-dcevm/blob/dcevm8u232b09/LICENSE

As you can see it is derivarion of GPL. You cold not use it in commercial projects without releasing your code.

**Comment by jhefreyzz** [comment]
Thank you for the response.
