### ISSUE TITLE
not able to start my tomcat server after patching my jdk

### ISSUE THREAD

**Issue by monaim** [dcevm/dcevm#176]
Hello, i would appreciate any help regarding the following issue:
i did this:

- i installed the DCEVM engine (DCEVM-8u181-installer-build2) into my jdk (jdk1.8.0_131)
- Configure the IDE to start the application with the HotswapAgent JAR as java agent by following 
  the steps in https://github.com/HotswapProjects/HotswapAgent/wiki/Eclipse-setup
- start tomact in debnug mode

afterwards i'm getting:

# A fatal error has been detected by the Java Runtime Environment:
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000057dfe36c, pid=35380, tid=0x00000000000089e4

# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Dynamic Code Evolution 64-Bit Server VM (25.71-b01-dcevmlight-26 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x1ae36c]

# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
# An error report file with more information is saved as:
# D:\IDEs\eclipse-jee-2019-06-R-win32-x86_64\hs_err_pid35380.log

# If you would like to submit a bug report, please visit:
#   https://github.com/dcevm/dcevm/issues
#
Dynamic Code Evolution 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

Thank you in davance

**Comment by skybber** [comment]
DCEVM-8u181 version should match with your jdk1.8.0_131, you should upgrade your jdk.

**Comment by monaim** [comment]
thank you Vladimir for your hint :o) 
It now works fine.
