### ISSUE TITLE
Questions about dcevm with HotswapAgent

### ISSUE THREAD

**Issue by jyf1997** [dcevm/dcevm#179]
I need to implement a jar package that can listen to changes in the jar and reload it into the jvm. Can dcevm and HotswapAgent achieve this kind of hot loading?

**Comment by skybber** [comment]
It is possible using `extraClasspath`.  Look at http://hotswapagent.org/mydoc_configuration.html . It's not possible to change jar file directly.  Classloader prefers classes on extraClasspath to classes from jar.
