### ISSUE TITLE
Document how to set options for integrated agent

### ISSUE THREAD

**Issue by cdalexndr** [dcevm/dcevm#191]
From original hotswap agent documentation:
`-javaagent:[yourpath/]hotswap-agent.jar=[option1]=[value1],[option2]=[value2]`

How to use these options when the agent is automatically loaded?

**Comment by skybber** [comment]
It is not necessary anymore.

**Comment by cdalexndr** [comment]
Why is that? How can I use `disablePlugin` option for instance?

**Comment by cdalexndr** [comment]
Ops, wrong project, was meant for `trava-jdk-11-dcevm`
