### ISSUE TITLE
Crashes when retransform classes that are used inside part of the jdk

### ISSUE THREAD

**Issue by dogourd** [dcevm/dcevm#210]
jdk: TravaOpenJDK-8u282b08
os: CentOS-7

List of classes in which the retransform operation is problematic:  
`java.net.URL`,
`java.io.File`,
`java.io.ByteArrayInputStream`,
`java.io.InputStream`,
`java.lang.StringBuilder`,
`java.lang.AbstractStringBuilder`,
`java.lang.System`,
`java.lang.Integer`,
`java.lang.Class`, // retransform it or not
`java.lang.String`,

1) if retransform the `java.lang.Class`  
Other classes in the above list will be considered illegal when they are redefined, and the corresponding error message is: `java.lang.InternalError: class redefinition failed: invalid class.`   
At the same time, other executing code will throw many exceptions, the corresponding information is: Execption: `java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.Class`  
The hs_err file and coredump file will not be generated after the process exits.

2) If do not retransform the class: `java.lang.Class`
From my log, `retransformClasses` can end normally at the level of java code execution, but the process crashes immediately at: `Internal Error (sharedRuntime.cpp:1175), pid=6932, tid=0x00007fce5ba53700 guarantee((retry_count++ < 100)) failed: Could not resolve to latest version of redefined method`.    
In this case, hs_err crash files and coredump files can be generated.

3) works on openjdk
At present it seems to be incompatible with dcevm，I tried to use openjdk8, it is compatible with my agent, the classes in the above list can be retransformed normally

**Comment by dogourd** [comment]
- Javaagent 
retransform `java.lang.String` without any ClassFileTransformer
![image](https://user-images.githubusercontent.com/32627020/210687779-06f665bf-a97e-4b7c-8d3c-03c3a20ba6b2.png)

- Application
Just start a springboot web application
![image](https://user-images.githubusercontent.com/32627020/210688062-a2ed0851-1eed-409c-a582-19f452ea907b.png)

- Result
![image](https://user-images.githubusercontent.com/32627020/210688354-ecd82338-e6a6-42da-8955-dbaf5fbdda34.png)

**Comment by skybber** [comment]
I did support for well-known classes redefinition for java11 and java17, may be someone could backport it to java8.
