### ISSUE TITLE
SUNWprivate_1.1 not defined in file libjvm.so

### ISSUE THREAD

**Issue by natros** [dcevm/dcevm#29]
I followed the build instructions (./gradlew patch && ./gradlew compileProduct && ./gradlew installProduct -PtargetJre=$JAVA_HOME/jre) but I'm getting not defined symbols

java -XXaltjvm=dcevm -version
Error occurred during initialization of VM
Unable to load native library: /usr/java/jdk1.7.0_60/jre/lib/amd64/libjava.so: symbol JVM_SetProtectionDomain, version SUNWprivate_1.1 not defined in file libjvm.so with link time reference

$ java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

$ arch && cat /etc/centos-release 
x86_64
CentOS release 6.5 (Final)

**Comment by candido1212** [comment]
Error occurred during initialization of VM
Unable to load native library: /home/desenv/jdk/jdk1.7.0_71/jre/lib/i386/libjava.so: symbol JVM_SetProtectionDomain, version SUNWprivate_1.1 not defined in file libjvm.so with link time reference

I want to run Jboss EAP 6.1

**Comment by hktalent** [comment]
@c4tom @idubrov @natros @mdaniel @ebourg 
```
see https://www.linuxquestions.org/questions/linux-desktop-74/java-issue-in-my-linux-machine-943077/

rm /usr/bin/java
update-alternatives --config java
rm /usr/bin/javac
update-alternatives --config javac


/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jli/libjli.so

rm /usr/lib/jvm/java-8-openjdk-amd64/bin/java
ln -s /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java /usr/lib/jvm/java-8-openjdk-amd64/bin/java
```
