### ISSUE TITLE
Create .exe installer for windows, request admin privilege

### ISSUE THREAD

**Issue by edudant** [dcevm/dcevm#39]
Standard Java installation on Windows requires administrator privilege to install DCEVM. When using .jar installer, the user gets "Please ensure that no other Java applications are running and you have sufficient permissions.", which may be confusing. I have seen a developer, who gave up installation DCEVM after killing all java processes, restarting computer and still getting this message.

This may be solved by creating windows .exe installer configured to ask for admin privilege: http://stackoverflow.com/questions/258728/request-admin-privileges-for-java-app-on-windows-vista.

A gradle plugin https://code.google.com/p/gradle-launch4j/wiki/Intro can be used to automate the build.

**Comment by JoyJava** [comment]
sudo java -jar xxx.jar

**Comment by ducquoc** [comment]
Work-around (tested on Windows 10): 

+ manually create a folder dcevm in %JAVA_HOME%/jre/bin and grant permissions for ALL_APPLICATION_PACKAGES  (or "Users") group; 
(given you are running an account with Administrator right - in Administrators group)

Then you can install DCEVM as altjvm using the GUI installer. 

Besides, you can launch the Windows command-line (cmd.exe) as Administrator 

https://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/

before 

```
java -jar DCEVM-light-8u112-installer.jar
```

hope this helps,

**Comment by skybber** [comment]
Workaround exists
