### ISSUE TITLE
More recent binary

### ISSUE THREAD

**Issue by barruda** [dcevm/dcevm#55]
Hi, first I want to thank you for keeping this project running... I setup the jdk8 + dcevm + tomee + intelliJ and it seems to be working fine... this is a real thing because using lambdas you are always changing the methods signatures and redepoloying for that would be a pain!! 

So, I looked at the patches and saw that there is a patch for update20 which is more recent... is it working fine? Do you plan to upload a binary? If so, I thank you very much in advance...

Best Regards

**Comment by develar** [comment]
+1, please publish DCEVM for latest JDK 8.

**Comment by andreasboos** [comment]
+1

**Comment by schweighart** [comment]
Instructions how to build on Windows are here: https://github.com/dcevm/dcevm/issues/60

**Comment by idubrov** [comment]
Java 8u45-based release published.
