### ISSUE TITLE
[OSX] dyld: lazy symbol binding failed: Symbol not found: _JVM_FindClassFromCaller

### ISSUE THREAD

**Issue by erikhakansson** [dcevm/dcevm#57]
When using JDK8u25 with installer-light-jdk8u5.52 I get the following error:

~~~
dyld: lazy symbol binding failed: Symbol not found: _JVM_FindClassFromCaller
  Referenced from: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libjava.dylib
JAVA_OPTS already set in environment; overriding default settings with values: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:50272,suspend=y,server=n -javaagent:/Users/xxx/Library/Caches/IntelliJIdea14/groovyHotSwap/gragent.jar -Xms2048m -Xmx2048m -XX:MaxPermSize=512m -javaagent:/Library/Java/Agents/hotswap-agent.jar -XXaltjvm=dcevm 
  Expected in: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/dcevm/libjvm.dylib

dyld: Symbol not found: _JVM_FindClassFromCaller
=========================================================================
  Referenced from: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libjava.dylib

  Expected in: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/dcevm/libjvm.dylib
~~~

This might have to do with the version difference, but on OSX Maverick, JDK8u5 is uninstallable due to a bug in the installer, and there's no release of DCEVM for newer builds yet.

**Comment by erikhakansson** [comment]
This seems to be the relevant change in the JDK:
http://hg.openjdk.java.net/bsd-port/jdk8/jdk/rev/cb621c3e79a1

From what I ca

**Comment by erikhakansson** [comment]
I managed to build a DCEVM targeting a JDK8u25 and it works perfectly! So it would be nice if some new binaries could be released. I suspect this is not an OSX issue so most new JDK8 releases might need new binaries.

**Comment by FearlessHyena** [comment]
hi Erik, I'm in the same boat and would like to use it with JDK8u30. Could you share what you had to do to make a build? Is it as simple as adding an entry in the gradle.properties for the new jdk (hotspotTag=jdk8u30-b99 for e.g.) and just building it?

**Comment by erikhakansson** [comment]
Yeah, that's what I did. I had some problems due to incompatibilites with Clang though. The compiler will complain about unknown flags. Simply go into the Makefile and remove those flags at the relevant places.

**Comment by erikhakansson** [comment]
Or build it with GCC, either on your Mac or on another computer, and just lift the compiled binary over.

**Comment by skybber** [comment]
You can use the dcevm8u20 build  in jdk8u25 and jdk8u30. It is  binary-compatible with them. Unfortunately dcevm8u20 is not available in binaries now. But you can build them from dcevm sources, just remove following comment in gradle.properties:
#hotspotTag=jdk8u20-b22

**Comment by FearlessHyena** [comment]
ah got it i'll try that. thanks for the information guys

**Comment by skybber** [comment]
Excuse me, I was wrong. There IS some compatibility issue between u20 and u25,u30.. I'll try to fix it.

**Comment by skybber** [comment]
There is a new fix for new versions >jdk8u20. You shoud uncomment 

#hotspotTag=jdk8u5-b13

in gradle.properties before build

**Comment by FearlessHyena** [comment]
great thanks @skybber. this one right? i'll check it out

#hotspotTag=jdk8u31-b13

**Comment by thodt-md** [comment]
#hotspotTag=jdk8u31-b13

Compilation failed with wrong argument format error until I manually commented out /hotspot/src/share/vm/prims/jvmtiRedefineClasses2.cpp:1540. Tests with Oracle JDK 1.8u31 ran successfully.

**Comment by idubrov** [comment]
8u45 build is available.
