### ISSUE TITLE
In readme.md is a dead link

### ISSUE THREAD

**Issue by hartmut27** [dcevm/dcevm#59]
In the readme.md is a dead link,   "pathes/" (typo?) points to https://github.com/dcevm/dcevm/blob/master/patches

Where have the patches gone?
Could this be the corerct pointer?: https://github.com/dcevm/dcevm/tree/master/hotspot/.hg/patches

"Supported versions
pathes/ contains patches for all supported versions. Each patch is named by concatenating prefix full or light with the OpenJDK HotSpot tag"

**Comment by idubrov** [comment]
Fixed a while ago.
