### ISSUE TITLE
Installer doesn't work on MacOS Oracle JDK 7u67

### ISSUE THREAD

**Issue by brendandobbs1** [dcevm/dcevm#61]
I get the following message when I run the dcevm-0.2-mac.jar installer

"Could not install to <JAVA_HOME>, 64 Bit Soylatte is not supported in this installer version"

Is there another way to setup dcevm without using the installer?

Thanks.

**Comment by fabiooshiro** [comment]
Any news?

**Comment by idubrov** [comment]
You can only use DCEVM with OpenJDK/Oracle JDK. Based on the installer message, you are trying to install it against Apple Java 6 (soylatte).

Most likely, installed just didn't detect location of your Java 7 installation properly and you need to point to it manually.

**Comment by brendandobbs1** [comment]
I got it working by using the light installer instead from here https://github.com/dcevm/dcevm/releases
