### ISSUE TITLE
"Conflicting collector combinations in option list" at jvm start 

### ISSUE THREAD

**Issue by kumm** [dcevm/dcevm#65]
I' built dcevm for jdk8u40 b25.
At "gradlew test", or after installing dcevm libjvm.so i get the mentioned error.
I'm on an Ubuntu 14.04 LTS.

After i've commented out the whole "if (os::is_server_class_machine()) {" in src/share/vm/runtime/arguments.cpp Arguments::select_gc_ergonomically() method and recompiled, it's working.

**Comment by idubrov** [comment]
Oh, I forgot to push changes.
