### ISSUE TITLE
gradlew patch bug

### ISSUE THREAD

**Issue by jduke32** [dcevm/dcevm#66]
There is no multilanguage support for dcevm.
I cant patch on turkish OS.
DCEVM should have multilanguage support
DCEVM sees OS name wrong because of no multilang support
it should see Windows but sees as  "w²ndows"

I have pasted error on below :

Build file 'C:\Users\USER\Desktop\dcevm\build.gradle' line: 265

* What went wrong:
A problem occurred evaluating root project 'dcevm'.
> Don't know how to detect os family "w²ndows"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

**Comment by jduke32** [comment]
i have changed the line
        return values().find { os -> org.apache.tools.ant.taskdefs.condition.Os.isFamily(os.name().toLowerCase()) }
to

        return values().find { os -> org.apache.tools.ant.taskdefs.condition.Os.isFamily("windows") }



has fixed the problem for windows

**Comment by idubrov** [comment]
Should be fixed now.
