### ISSUE TITLE
Will there be a binary release for more recent versions of jdk?

### ISSUE THREAD

**Issue by ravshansbox** [dcevm/dcevm#68]

**Comment by andreasboos** [comment]
+1

**Comment by idubrov** [comment]
I am currently setting my build environment for Java 8u45. Can't guarantee anything, but hope to build binary soon.

**Comment by idubrov** [comment]
Published Java 8u45

**Comment by ravshansbox** [comment]
Wow, that's great, thank you.

**Comment by ravshansbox** [comment]
how about the full version for later jdk7?
