### ISSUE TITLE
java/util/HashMap$Entry error

### ISSUE THREAD

**Issue by oallauddin** [dcevm/dcevm#75]
Testing latest version DCEVM (light) for Java 8u45 (build 15) with Java8u45 64 bit and Grails/Groovy.

Getting HashMap#Entry error similar to the below posts.
https://github.com/nextflow-io/nextflow/issues/7
https://groups.google.com/forum/#!msg/groovy-user/MeHXv6fz15o/mkrB4VjXGJsJ

**Comment by idubrov** [comment]
This is not a DCEVM issue. This issue happens when code relies on implementation detail of HashMap which was changed in Java 8 (inner class "Entry").
