### ISSUE TITLE
Logging should be reduced when in production mode

### ISSUE THREAD

**Issue by vpablos** [dcevm/dcevm#86]
When in production mode DCEVM still logs too much. Messages are like:

(-1 / -1) (org/hotswap/agent/plugin/jvm/AnonymousClassInfos$AnonymousClassInfoMatcher/org/hotswap/agent/plugin/jvm/AnonymousClassInfos$AnonymousClassInfoMatcher)
{instance class} 
 - klass: {other class}
{instance class} 
 - klass: {other class}

Please, reduce logging by applying the patch in
https://github.com/HotswapProjects/HotswapAgent/issues/57
or something similar.

Thanks in advance.

**Comment by cchilds** [comment]
I am also experiencing this issue and it is very annoying. A fix would be much appreciated.

**Comment by vnom2112** [comment]
Same here, would love to see this fixed.

**Comment by PrabakaranSK** [comment]
A must needed fix ASAP.

**Comment by ronaldtm** [comment]
On the other hand, should you even be using this in production? o_O

**Comment by cchilds** [comment]
This is not just an issue in production. It's very hard to debug when your logs and stack traces are lost in a sea of annoying, useless messages.

**Comment by idubrov** [comment]
Try this release: https://github.com/dcevm/dcevm/releases/tag/full-jdk7u79%2B8

Does it reduce amount of logging?

**Comment by cchilds** [comment]
Wow, this is fantastic. That works great. Thank you so much!

**Comment by PrabakaranSK** [comment]
Will it also work with JDK 7 u55 (Windows)?
