### ISSUE TITLE
Annotations on wrong methods after redefinition

### ISSUE THREAD

**Issue by erkieh** [dcevm/dcevm#88]
Hi!

I am having issues where annotations end up on the wrong methods after redefinition.

I was unable to reproduce this issue in the DCEVM AnnotationTest, but was able to create a small example reproducing the error.  
https://gist.github.com/erkieh/de823938034767d685df

Run the main method in a jvm with dcevm enabled. 
After the first iteration has occurred ("INFO - sleeping for 3000 ms" - is printed to the console), 
uncomment the method named "b" in the inner static class A. The following error should be printed to the console on the next iteration.
ERROR - method: b, annotation: a
ERROR - method: a, annotation: b

This indicates, that for some reason the method name and the value in the annotation do not match in runtime, although they do in the source code.

**Comment by edudant** [comment]
I have solved similar issue in  the [HotswapAgent](http://hotswapagent.org/) subproject: 
https://github.com/HotswapProjects/HotswapAgent/tree/master/hotswap-agent-core/src/main/java/org/hotswap/agent/plugin/jvm

**Comment by erkieh** [comment]
I think a plugin for HotswapAgent that would shuffle the annotations around, so that they would be on the expected methods, would only work in limited situations. You can determine the correct mapping only when one method is changed/added?
Though this would probably cover the most frequent use cases.

**Comment by skybber** [comment]
fixed
