### ISSUE TITLE
LinkageError with reflection in java 1.8

### ISSUE THREAD

**Issue by spelletier** [dcevm/dcevm#94]
When redefining a class used in an argument of a method called with Reflexion in Java 1.8_66, I get this error. I do not experience this with java 1.7.

java.lang.LinkageError: loader constraint violation: when resolving method "com.gestioncarrieres.gestion.components.organisme.DossierListViewer.setDossier(Lcom/gestioncarrieres/model/admin/Dossier;)V" the class loader (instance of sun/reflect/DelegatingClassLoader) of the current class, sun/reflect/GeneratedMethodAccessor79, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, com/gestioncarrieres/gestion/components/organisme/DossierListViewer, have different Class objects for the type com/gestioncarrieres/model/admin/Dossier used in the signature
  at sun.reflect.GeneratedMethodAccessor79.invoke(null:Unknown)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at com.webobjects.foundation.NSKeyValueCoding$ValueAccessor$1.setMethodValue(NSKeyValueCoding.java:643)

**Comment by idubrov** [comment]
Should be fixed in 8u74 update:

https://github.com/dcevm/dcevm/releases/tag/light-jdk8u74%2B1

**Comment by spelletier** [comment]
Seems fixed, I used it all day with no LinkageError.

Thank you for the fix.
