### ISSUE TITLE
Crashing with linux and oracle jdk 8

### ISSUE THREAD

**Issue by eduardoschmidtsantos** [dcevm/dcevm#96]
A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f28100d2be0, pid=7118, tid=139809983915776

 JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
 Java VM: Dynamic Code Evolution 64-Bit Server VM (25.66-b00-dcevmlight-5 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.so+0x4ccbe0]  ConstantPool::klass_ref_at_noresolve(int)+0x60

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   https://github.com/dcevm/dcevm/issues

---

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f75d51e1e0c, pid=9151, tid=140143673870080

 JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
 Java VM: Dynamic Code Evolution 64-Bit Server VM (25.66-b00-dcevmlight-5 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.so+0x74be0c]  VM_EnhancedRedefineClasses::load_new_class_versions(Thread*)+0x2cc

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   https://github.com/dcevm/dcevm/issues

**Comment by nenodias** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f62bfe4abe0, pid=31767, tid=140062044157696
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Dynamic Code Evolution 64-Bit Server VM (25.66-b00-dcevmlight-5 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x4ccbe0]  ConstantPool::klass_ref_at_noresolve(int)+0x60
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

**Comment by skybber** [comment]
Not enough info supplied, please send hs_err_pid*.log next time.
