### ISSUE TITLE
Installation as altvm does not seem enhance class reloading capabilities

### ISSUE THREAD

**Issue by OndrejM** [dcevm/dcevm#97]
Installation as altvm does not seem to enhance class reloading capabilities (e.g. method rename does not work). On the other hand, when installed as replacing by DCEVM (using graphical installer), hot method renaming works as expected.

Details:
 - version of DCEVM installer: DCEVM-light-8u74-installer.jar
 - JVM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03, mixed mode)
 - Java: version 1.8.0_77, vendor Oracle Corporation
 - OS: Ubuntu Linux 15.10

**Comment by skybber** [comment]
I've no problems it on ArchLinux, using JVM argument -XXaltjvm=dcevm
```bash
skybber@skybber /usr/lib/jvm/java-8-openjdk/jre/lib/amd64/dcevm $ ls -l
total 15708
-rwxr-xr-x 1 skybber skybber 16084824 Mar 26 14:25 libjvm.so
```

**Comment by OndrejM** [comment]
Thank you for your feedback. I found out that I had -client in the list of params to java command, and it was taking precedence over -XXaltjvm option. Maybe it would be good to point that out in installation guides.
Closing this issue.
