### ISSUE TITLE
Weblogic server crashing with DCEVM

### ISSUE THREAD

**Issue by 24adithya** [dcevm/dcevm#98]
Hi,

I am having Java version as 1.7_67 and DCEVM version as 1.7_71. I have installed DCEVM as altjvm. 

Whenever i am changing the code and compiling the class file in IDE and my server debugger is on, i think while reloading something is going wrong and my server is crashing with the following message:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000007d46180, pid=25304, tid=24784
#
# JRE version: Java(TM) SE Runtime Environment (7.0_67-b01) (build 1.7.0_67-b01)
# Java VM: Dynamic Code Evolution 64-Bit Server VM (24.71-b01-dcevmlight-2 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x176180]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Oracle\MIDDLE~2\user_projects\domains\GasOps\hs_err_pid25304.log
#
# If you would like to submit a bug report, please visit:
#   http://ssw.jku.at/dcevm/bugreport/
#
```

When my debugger is off and i am making the changes, the server doesn't shut down but the changes aren't reflected.

I am not launching the server via IDE. Secondly, on jetty server where i am running spring, it seems to pick the changes correctly but i get the following message on console as follows:

```
HOTSWAP AGENT: 13:27:6.354 ERROR (org.hotswap.agent.plugin.spring.signature.ClassfileSignatureComparer) - Error reading siganture
org.hotswap.agent.javassist.NotFoundException: com.sungard.energy.aligne.aligneweb.scheduling.LoadsDVO
        at org.hotswap.agent.javassist.ClassPool.get(ClassPool.java:445)
        at org.hotswap.agent.javassist.bytecode.Descriptor.toCtClass(Descriptor.java:577)
        at org.hotswap.agent.javassist.bytecode.Descriptor.getParameterTypes(Descriptor.java:430)
        at org.hotswap.agent.javassist.CtBehavior.getParameterTypes(CtBehavior.java:286)
        at org.hotswap.agent.plugin.spring.signature.CtClassSignature.getMethodString(CtClassSignature.java:35)
        at org.hotswap.agent.plugin.spring.signature.CtClassSignature.get(CtClassSignature.java:65)
        at org.hotswap.agent.plugin.spring.signature.ClassfileSignatureComparer.isPoolClassDifferent(ClassfileSignatureComparer.java:24)
        at org.hotswap.agent.plugin.spring.SpringChangesAnalyzer.classChangeNeedsReload(SpringChangesAnalyzer.java:43)
        at org.hotswap.agent.plugin.spring.SpringChangesAnalyzer.isReloadNeeded(SpringChangesAnalyzer.java:36)
        at org.hotswap.agent.plugin.spring.SpringPlugin$1.transform(SpringPlugin.java:80)
        at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:129)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
```

I have specified `extraClassPath` and set `autoHotSwap=true` in both the cases in the properties file.

My hotswap agent version is 0.3.

Is there a way to know more information or get around these problems ?

**Comment by prasadbolla** [comment]
Hi Adithya,
I have not able to start my weblogic 10.3.6 when I update the startWeblogic.cmd with hotSwap agent. Can you help me out in setting up ? thanks

**Comment by skybber** [comment]
This thread was not based for Weblogic problems. Anyway weblogic is not supported by HA since it is closed source.

**Comment by skybber** [comment]
Problem is linked with usage of dcevm7 which is retired now

**Comment by ramuece09** [comment]
@skybber  So, is that working with weblogic now?

**Comment by skybber** [comment]
Probably not.

**Comment by ramuece09** [comment]
@skybber Thanks for your response! Do we have any other alternatives? I am looking for similar to JREBEL with web logic server. Any suggestions much appreciated. Thanks again for your time :)

**Comment by Vivsaxena59** [comment]
Is the issue still persist with Weblogic server. I am trying to configure DCEVM but its not picking up the changes.
I have followed below process:
1. Download DCEVM-light-8u66-installer.jar and installed it in my java directory (using Java 8 u181)
2. Added below line in setDomainEnv.cmd
set JAVA_OPTIONS=%JAVA_OPTIONS% -XXaltjvm=dcevm
3. Started the weblogic server. 

Server is getting started without any issus and able to see the DCEVM is initialized. Tried to make a method changes but its not picking up

**Comment by skybber** [comment]
Weblogic is closed sources project. It is impossible to make a plugin without them.

**Comment by Nahalovka** [comment]
> Is the issue still persist with Weblogic server. I am trying to configure DCEVM but its not picking up the changes. I have followed below process:
> 
> 1. Download DCEVM-light-8u66-installer.jar and installed it in my java directory (using Java 8 u181)
> 2. Added below line in setDomainEnv.cmd
>    set JAVA_OPTIONS=%JAVA_OPTIONS% -XXaltjvm=dcevm
> 3. Started the weblogic server.
> 
> Server is getting started without any issus and able to see the DCEVM is initialized. Tried to make a method changes but its not picking u
Which jdk  you use?
